# Temperature Display App - Pre-commit Configuration
# Docker-based code quality tools and hooks
# Run with: pre-commit run --all-files

repos:
  # Standard pre-commit hooks for basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
        description: Removes trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files
        description: Ensures files end in a newline
      - id: check-yaml
        name: Check YAML syntax
        description: Validates YAML files
      - id: check-json
        name: Check JSON syntax
        description: Validates JSON files
      - id: check-merge-conflict
        name: Check for merge conflicts
        description: Prevents committing merge conflict markers
      - id: check-added-large-files
        name: Check for large files
        description: Prevents committing large files
        args: ['--maxkb=1000']
      - id: check-docstring-first
        name: Check docstring placement
        description: Ensures docstrings come first
      - id: check-executables-have-shebangs
        name: Check executable shebangs
        description: Ensures executables have shebangs
      - id: check-shebang-scripts-are-executable
        name: Check shebang executables
        description: Ensures shebang scripts are executable

  # Python code formatting with Black
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        name: Format code with Black
        description: Python code formatter
        language_version: python3.11
        args: [--line-length=88, --target-version=py311]

  # Import sorting with isort (configured for Black compatibility)
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Sort imports with isort
        description: Python import sorter
        args: [--profile=black, --line-length=88]

  # Code linting with flake8
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: Lint with flake8
        description: Python linter
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
        args:
          - --max-line-length=88
          - --extend-ignore=E203,W503,E501
          - --exclude=migrations,__pycache__,.git,.tox,.eggs,*.egg
        exclude: ^(migrations/|alembic/versions/)

  # Type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        name: Type check with mypy
        description: Static type checker
        additional_dependencies:
          - types-redis
          - types-requests
          - types-PyYAML
          - sqlalchemy[mypy]
          - pydantic
        args:
          - --ignore-missing-imports
          - --disallow-untyped-defs
          - --check-untyped-defs
        exclude: ^(migrations/|alembic/versions/|tests/)

  # Security linting with bandit
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: Security check with bandit
        description: Security linter
        args: [-r, ., -f, json, -x, tests/,migrations/]
        exclude: ^tests/

  # Documentation style checking
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        name: Check docstring style
        description: Docstring style checker
        args: [--convention=google]
        exclude: ^(migrations/|alembic/versions/|tests/)

  # Docker-specific checks
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: Lint Dockerfiles
        description: Dockerfile linter
        args: [--ignore, DL3008, --ignore, DL3009]

  # YAML formatting and validation
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: Format with Prettier
        description: Code formatter for various languages
        files: \.(yaml|yml|json|md)$
        exclude: ^(.pre-commit-config.yaml)$

# Global configuration
default_language_version:
  python: python3.11

# Global exclude patterns
exclude: |
  (?x)^(
      migrations/.*\.py|
      alembic/versions/.*\.py|
      __pycache__/.*|
      \.git/.*|
      \.tox/.*|
      \.venv/.*|
      venv/.*|
      build/.*|
      dist/.*|
      \.eggs/.*
  )$

# CI integration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false 